# Generated by Django 4.2 on 2023-04-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_account_phone_number_alter_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_number",
            field=models.CharField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
