# Generated by Django 4.2 on 2023-04-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_phone_number_alter_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
